export const projects = [
  {
    id: 1,
    name: "Sushi Website",
    category: "HTML & CSS",
    img: "/src/assets/mk-sushi-web.webp",
    url: "https://suki1207.github.io/sushi-website/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 2,
    name: "Tribute: Girl with a Pearl Earring",
    category: "HTML & CSS",
    img: "/src/assets/mk-tribute-pg.webp",
    url: "https://suki1207.github.io/tribute-page/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 3,
    name: "Amazon Clone",
    category: "JavaScript",
    img: "/src/assets/mk-amazon-cl.webp",
    url: "https://suki1207.github.io/amazon-clone/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 4,
    name: "Coffee Website",
    category: "HTML & CSS",
    img: "/src/assets/mk-coff-web.webp",
    url: "https://suki1207.github.io/coffee-website/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 5,
    name: "Website Wireframe",
    category: "Figma",
    img: "/src/assets/mk-web-wirefr.webp",
    url: "https://www.figma.com/design/wDcO93G2ScmtCdYuFGPSgH/Website-Wireframe?node-id=0-1&t=8Y5Qw2OI34ybaXFi-1",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 6,
    name: "YouTube Clone",
    category: "HTML & CSS",
    img: "/src/assets/mk-youtube-cl.webp",
    url: "https://suki1207.github.io/youtube-clone/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 7,
    name: "Little Lemon Booking",
    category: "React",
    img: "/src/assets/mk-little-lemon.webp",
    url: "https://suki1207.github.io/little-lemon-home-booking/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 8,
    name: "Todo List",
    category: "JavaScript",
    img: "/src/assets/mk-todo-list.webp",
    url: "https://suki1207.github.io/todo-list/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 9,
    name: "Coffee Landing Page",
    category: "HTML & CSS",
    img: "/src/assets/mk-coffee-land-pg.webp",
    url: "https://suki1207.github.io/coffee-landing-page/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 10,
    name: "React Calculator",
    category: "React",
    img: "/src/assets/mk-react-calc.webp",
    url: "https://suki1207.github.io/react-calculator-app/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 11,
    name: "Chatbot",
    category: "React",
    img: "/src/assets/mk-react-chatbot.webp",
    url: "https://suki1207.github.io/chatbot-react/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 12,
    name: "Apple Calculator",
    category: "JavaScript",
    img: "/src/assets/mk-apple-calc.webp",
    url: "https://suki1207.github.io/apple-calculator/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 13,
    name: "Rock Paper Scissors Game",
    category: "JavaScript",
    img: "/src/assets/mk-r-p-s-game.webp",
    url: "https://suki1207.github.io/rock-paper-scissors-game/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 14,
    name: "Boxes Challenge",
    category: "React",
    img: "/src/assets/mk-boxes-chall.webp",
    url: "https://suki1207.github.io/boxes-challenge/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 15,
    name: "AirBnB",
    category: "React",
    img: "/src/assets/mk-airbnb-cl.webp",
    url: "https://suki1207.github.io/airbnb-clone/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 16,
    name: "Pokémon Search",
    category: "JavaScript",
    img: "/src/assets/mk-poké-sear.webp",
    url: "https://suki1207.github.io/pokemon-search-app/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 17,
    name: "Roman Numeral Converter",
    category: "JavaScript",
    img: "/src/assets/mk-rom-num-converter.webp",
    url: "https://suki1207.github.io/roman-numeral-converter/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
  {
    id: 18,
    name: "Palindrome Checker",
    category: "JavaScript",
    img: "/src/assets/mk-pali-checker.webp",
    url: "https://suki1207.github.io/palindrome-checker/",
    icon: `<i class="fa-solid fa-arrow-up-right-from-square"></i>`,
  },
];
